module.exports = {
  CREATED_BY_OWNER: 'CREATED_BY_OWNER',
  CREATED_BY_USER : 'CREATED_BY_USER',
  CONFIRMED_BY_OWNER: 'CONFIRMED_BY_OWNER',
  UNCONFIMED_BY_OWNER: 'UNCONFIMED_BY_OWNER',
  DELETED_BY_USER: 'DELETED_BY_USER'
}